#include "granja/Save.hpp"
#include "granja/TouchControls.hpp"
#include <fstream>
#include <iostream>
#include <nlohmann/json.hpp>
#include <functional>
#include <queue>
#include <set>
#include <stdexcept>
using namespace granja;
static void check(bool ok,const char* message) { if(!ok) throw std::runtime_error(message); }
static void close(float a,float b,float epsilon=.01f) { check(std::abs(a-b)<epsilon,"Numeric mismatch"); }
static void clearEnemies(Simulation& s) {for(auto& [k,c]:s.world.chunks())c.enemies.clear();}
int main() {
    int passed=0,failed=0;
    auto test=[&](const char* name,const std::function<void()>& run){try{run();++passed;std::cout<<"PASS "<<name<<'\n';}catch(const std::exception& e){++failed;std::cerr<<"FAIL "<<name<<": "<<e.what()<<'\n';}};
    test("multitouch move and attack have independent owners",[]{TouchControls t;t.resize(844,390);check(t.down(4,t.stick)==TouchControls::Action::Joystick,"Joystick not captured");t.move(4,t.stick+Vec{t.radius,0});check(t.down(8,t.attackButton)==TouchControls::Action::Attack,"Attack not captured");auto input=t.sample();check(input.attack&&input.move.x>.99f,"Two fingers conflict");t.up(8);input=t.sample();check(!input.attack&&input.move.x>.99f,"Attack release stopped movement");t.up(4);check(length(t.sample().move)==0,"Joystick stuck after release");});
    test("touch cancellation, dead zone, pulses and resize",[]{TouchControls t;t.resize(390,844);t.down(1,t.stick);t.move(1,t.stick+Vec{2,0});check(length(t.sample().move)==0,"Dead zone failed");t.move(1,t.stick+Vec{1000,0});close(length(t.sample().move),1);t.down(2,t.dodgeButton);check(t.sample().dodge&&!t.sample().dodge,"Dodge repeated while held");t.down(3,t.attackButton);t.reset();auto i=t.sample();check(!i.attack&&length(i.move)==0,"Cancel retained controls");t.resize(844,390);check(t.stick.y<390&&t.attackButton.x<844,"Resize broke layout");});
    test("partial analog deflection scales speed",[]{Simulation s;clearEnemies(s);auto origin=s.player.pos;s.update(.05f,{{.5f,0}});close(distance(s.player.pos,origin),s.player.speed()*.05f*.5f);close(length(s.player.facing),1);});
    test("deterministic terrain, loot and seed variation",[]{World a(42),b(42),c(43);int changed=0;for(int y=-30;y<30;++y)for(int x=-30;x<30;++x){check(a.terrain(x,y)==b.terrain(x,y),"Seed is unstable");changed+=a.terrain(x,y)!=c.terrain(x,y);}check(changed>10,"Seeds do not change world");auto& ac=a.ensure({2,-2});auto& bc=b.ensure({2,-2});check(ac.loot.size()==bc.loot.size(),"Loot unstable");for(std::size_t i=0;i<ac.loot.size();++i){close(ac.loot[i].pos.x,bc.loot[i].pos.x);check(ac.loot[i].kind==bc.loot[i].kind,"Loot mismatch");}});
    test("negative chunk coordinates and bounded active set",[]{check(chunkAt({-1,-1025})==ChunkKey{-1,-2},"Negative coordinates truncated");World w;w.stream({0,0});check(w.active().size()==9,"Wrong active radius");w.stream({4096,-2048});check(w.active().size()==9 && w.active().contains({4,-2}) && !w.active().contains({0,0}),"Streaming failed");check(w.chunks().size()==9,"Inactive chunk was not unloaded");});
    test("chunk unloading preserves collected items and defeats",[]{World w;w.stream({160,160});auto& c=w.ensure({0,0});c.loot.front().collected=true;int id=c.loot.front().id;w.stream({5000,5000});check(!w.chunks().contains({0,0}),"Old chunk retained");w.stream({160,160});auto& loaded=w.ensure({0,0});check(std::find_if(loaded.loot.begin(),loaded.loot.end(),[id](const Loot& l){return l.id==id;})->collected,"Unload lost loot state");});
    test("swept water collision prevents tunneling",[]{World w;bool found=false;for(int y=-30;y<30&&!found;++y)for(int x=-30;x<30&&!found;++x){Vec p{(x+.5f)*64,(y+.5f)*64};Vec left=p-Vec{64,0};if(w.terrain(x,y)==Terrain::Water&&!w.blocked(left,18)){Vec result=w.move(left,{128,0},18);check(result.x<p.x-30,"Tunneled through water");check(!w.blocked(result,18),"Ended in obstacle");found=true;}}check(found,"No representative water edge found");});
    test("spawn can reach boss, secret grove and quest resources",[]{
        World w;std::queue<ChunkKey> queue;std::set<ChunkKey> visited;queue.push({2,2});visited.insert({2,2});
        while(!queue.empty()) {
            auto k=queue.front();queue.pop();Vec p{(k.x+.5f)*64,(k.y+.5f)*64};
            for(auto delta:std::vector<ChunkKey>{{1,0},{-1,0},{0,1},{0,-1}}) {
                ChunkKey next{k.x+delta.x,k.y+delta.y};if(std::abs(next.x)>35||std::abs(next.y)>35||visited.contains(next))continue;
                Vec dest{(next.x+.5f)*64,(next.y+.5f)*64};if(distance(w.move(p,dest-p,18),dest)<.1f){visited.insert(next);queue.push(next);}
            }
        }
        auto tile=[](Vec p){return ChunkKey{int(std::floor(p.x/64)),int(std::floor(p.y/64))};};
        check(visited.contains(tile(World::bossHome)),"Boss unreachable");check(visited.contains(tile(World::secretHome)),"Secret grove unreachable");
        int eggs=0,gold=0,rivals=0;for(int y=-2;y<=2;++y)for(int x=-2;x<=2;++x){const auto& c=w.ensure({x,y});for(const auto& item:c.loot)if(visited.contains(tile(item.pos))){eggs+=item.kind==LootKind::Egg;gold+=item.kind==LootKind::GoldenEgg;}for(const auto& e:c.enemies)if(!e.boss&&visited.contains(tile(e.pos)))++rivals;}
        check(eggs>=6&&gold>=2&&rivals>=5,"Not enough reachable quest resources");
    });
    test("diagonal movement normalization",[]{Simulation a,b;clearEnemies(a);clearEnemies(b);a.update(.05f,{{1,0}});b.update(.05f,{{1,1}});close(distance(a.player.pos,World::nest),distance(b.player.pos,World::nest));});
    test("pickup rewards exactly once",[]{Simulation s;auto& c=s.world.ensure({0,0});c.loot={{1,s.player.pos,LootKind::Egg,false},{2,s.player.pos,LootKind::GoldenEgg,false},{3,s.player.pos,LootKind::Chest,false}};s.collect();check(s.player.eggs==1&&s.player.goldenEggs==1&&s.player.coins==68&&s.player.food==5,"Incorrect loot rewards");s.collect();check(s.player.coins==68&&s.player.eggs==1,"Duplicate collection");});
    test("directional combat, cooldown, death and XP",[]{Simulation s;clearEnemies(s);auto& c=s.world.ensure({0,0});c.enemies={{1,{220,160},{220,160},20,20},{2,{100,160},{100,160},75,75}};s.attack({1,0});check(c.enemies[0].hp==0&&c.enemies[1].hp==75,"Attack cone failed");check(s.player.kills==1&&s.player.coins==12&&s.player.xp==25,"Kill rewards missing");s.attack({1,0});check(s.player.kills==1,"Duplicate kill reward");close(s.player.stamina,88);});
    test("NPC windup can damage and dodge protects",[]{Simulation s;clearEnemies(s);s.player.pos={500,160};auto& c=s.world.ensure({0,0});Enemy e{1,{545,160},{545,160},100,100};e.brain=Brain::Windup;e.aim={-1,0};e.timer=.01f;c.enemies.push_back(e);s.update(.02f,{});check(s.player.hp==86,"Telegraphed attack did not hit");s.player.hp=100;s.player.pos={500,160};s.player.invulnerable=0;c.enemies[0].brain=Brain::Windup;c.enemies[0].timer=.01f;Input i;i.dodge=true;i.move={0,1};s.update(.02f,i);close(s.player.hp,100);check(s.player.stamina<80,"Dodge cost missing");});
    test("death respawns and keeps inventory",[]{Simulation s;clearEnemies(s);s.player.pos={500,160};s.player.hp=1;s.player.coins=100;s.player.eggs=8;Enemy e{1,{545,160},{545,160},100,100};e.brain=Brain::Windup;e.timer=.01f;e.aim={-1,0};s.world.ensure({0,0}).enemies.push_back(e);s.update(.02f,{});close(distance(s.player.pos,World::nest),0);check(s.player.deaths==1&&s.player.coins==90&&s.player.eggs==8&&s.saveRequested,"Respawn contract failed");});
    test("healing inventory and no full-health waste",[]{Simulation s;clearEnemies(s);s.player.hp=40;Input i;i.eat=true;s.update(.02f,i);close(s.player.hp,85);check(s.player.food==2,"Food not consumed");s.player.hp=s.player.maxHp();s.update(.02f,i);check(s.player.food==2,"Food wasted");});
    test("level growth and upgrade economy",[]{Simulation s;s.addXp(250);check(s.player.level==3&&s.player.xp==10,"XP rollover wrong");s.player.coins=100;check(s.upgrade(1),"Upgrade failed");check(s.player.coins==70&&s.player.attackUp==1,"Wrong upgrade price");s.player.pos={500,160};check(!s.upgrade(1),"Upgrade allowed away from home");});
    test("boss gate, victory and no repeated reward",[]{Simulation s;s.player.pos=World::bossHome-Vec{60,0};s.world.stream(s.player.pos);auto& c=s.world.ensure(chunkAt(World::bossHome));auto it=std::find_if(c.enemies.begin(),c.enemies.end(),[](const Enemy& e){return e.boss;});check(it!=c.enemies.end(),"Boss absent");it->hp=20;s.attack({1,0});check(it->hp==20,"Gate ignored");s.player.eggs=6;s.player.goldenEggs=2;s.player.kills=5;s.player.attackCooldown=0;s.player.stamina=100;s.attack({1,0});check(s.player.bossDefeated&&s.victoryEvent&&it->rewarded&&s.player.coins==150,"Victory missing");s.player.attackCooldown=0;s.attack({1,0});check(s.player.coins==150,"Boss rewards repeated");});
    auto path=std::filesystem::temp_directory_path()/"granja-gameplay-tests"/"save.json";
    test("JSON round trip preserves world and defeated enemy",[&]{Simulation s;auto& c=s.world.ensure({0,0});c.loot.front().collected=true;auto lootId=c.loot.front().id;auto& rivals=s.world.ensure({1,0});check(!rivals.enemies.empty(),"No test enemy");rivals.enemies.front().hp=0;rivals.enemies.front().rewarded=true;auto enemyId=rivals.enemies.front().id;s.player.coins=97;s.player.eggs=9;s.player.healthUp=2;s.player.hp=123;std::string error;check(Save::write(s,path,error),error.c_str());Simulation loaded(123);check(Save::read(loaded,path,error),error.c_str());check(loaded.world.seed()==s.world.seed()&&loaded.player.coins==97&&loaded.player.healthUp==2,"Player or seed lost");close(loaded.player.hp,123);auto& lc=loaded.world.ensure({0,0});check(std::find_if(lc.loot.begin(),lc.loot.end(),[lootId](const Loot& l){return l.id==lootId;})->collected,"Collected egg restored");auto& le=loaded.world.ensure({1,0});check(std::find_if(le.enemies.begin(),le.enemies.end(),[enemyId](const Enemy& e){return e.id==enemyId;})->rewarded,"Enemy respawned");s.player.coins=104;check(Save::write(s,path,error)&&Save::read(loaded,path,error),"Existing save replacement failed");check(loaded.player.coins==104,"Overwrite failed");});
    test("save includes unloaded explored chunks",[&]{Simulation s;auto& c=s.world.ensure({0,0});c.loot.front().collected=true;int id=c.loot.front().id;s.player.pos={5000,160};s.world.stream(s.player.pos);check(!s.world.chunks().contains({0,0}),"Chunk still active");std::string error;check(Save::write(s,path,error),error.c_str());Simulation loaded;check(Save::read(loaded,path,error),error.c_str());auto& home=loaded.world.ensure({0,0});check(std::find_if(home.loot.begin(),home.loot.end(),[id](const Loot& item){return item.id==id;})->collected,"Dormant chunk omitted from save");});
    test("invalid save rejection is transactional",[&]{std::ifstream in(path);nlohmann::json j;in>>j;j["player"]["hp"]=-20;in.close();std::ofstream(path)<<j.dump();Simulation s;s.player.coins=777;std::string error;check(!Save::read(s,path,error)&&!error.empty(),"Invalid save accepted");check(s.player.coins==777,"Failed load changed state");std::ofstream(path)<<"{broken";check(!Save::read(s,path,error),"Corrupt JSON accepted");});
    std::filesystem::remove_all(path.parent_path());
    std::cout<<passed<<" passed, "<<failed<<" failed\n";return failed?1:0;
}
