# Optional Windows cross build using the isolated Debian MinGW toolchain.
set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR AMD64)
set(GRANJA_MINGW_ROOT /workspace/toolchain/sysroot/usr CACHE PATH "Relocated MinGW root")
set(CMAKE_C_COMPILER "${GRANJA_MINGW_ROOT}/bin/x86_64-w64-mingw32-gcc-posix")
set(CMAKE_CXX_COMPILER "${GRANJA_MINGW_ROOT}/bin/x86_64-w64-mingw32-g++-posix")
set(CMAKE_RC_FLAGS_INIT "--preprocessor=${GRANJA_MINGW_ROOT}/bin/x86_64-w64-mingw32-gcc-posix --preprocessor-arg=-E --preprocessor-arg=-xc --preprocessor-arg=-DRC_INVOKED")
set(CMAKE_RC_COMPILER "${GRANJA_MINGW_ROOT}/bin/x86_64-w64-mingw32-windres")
set(CMAKE_FIND_ROOT_PATH "${GRANJA_MINGW_ROOT}/x86_64-w64-mingw32")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
set(SFML_USE_SYSTEM_DEPS OFF CACHE BOOL "" FORCE)
set(CMAKE_EXE_LINKER_FLAGS_INIT "-static-libgcc -static-libstdc++ -static")
