const $=id=>document.getElementById(id),canvas=$('game'),ctx=canvas.getContext('2d',{alpha:false});
const Module=await createGranja();
const loadImage=src=>new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=()=>reject(new Error(`Recurso não carregado: ${src}`));img.src=src;});
let walk,actions;
try{[walk,actions]=await Promise.all([loadImage('assets/chicken-walk.png'),loadImage('assets/chicken-actions.png')]);}
catch(e){$('start').textContent='Falha ao carregar imagens';$('menuText').textContent=e.message;throw e;}
let w=0,h=0,scale=1,state=null,paused=true,started=false,showQuest=false,last=0,acc=0,autosave=0,mouseAttack=false,mouseWorld=null,workshopRequested=false,won=false;
const keys=new Set(),pointers=new Map();let pulses=0;const storageKey='meu-galinheiro-save-v1';
const api={snapshot:(a,b)=>JSON.parse(Module.UTF8ToString(Module._game_snapshot(a,b))),save:()=>Module.UTF8ToString(Module._game_save()),load:s=>Module.ccall('game_load','number',['string'],[s])};
function resize(){w=innerWidth;h=innerHeight;const dpr=Math.min(devicePixelRatio||1,1.5);canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);scale=Math.min(1.3,Math.max(.8,Math.min(w/800,h/500)));Module._game_resize(w,h);pointers.clear();mouseAttack=false;}
addEventListener('resize',resize);resize();
function persist(){try{const data=api.save();if(!data)throw new Error('save vazio');localStorage.setItem(storageKey,data);$('saveStatus').textContent='Progresso salvo neste navegador.';return true;}catch(e){$('saveStatus').textContent='Não foi possível salvar neste navegador.';return false;}}
let existing=false;try{const saved=localStorage.getItem(storageKey);if(saved)existing=!!api.load(saved);}catch{};
$('start').disabled=false;$('start').textContent=existing?'Continuar aventura':'Começar aventura';$('new').hidden=!existing;
function cancelInput(){Module._game_cancel_input();pointers.clear();keys.clear();mouseAttack=false;pulses=0;mouseWorld=null;}
function play(){paused=false;started=true;cancelInput();$('modal').hidden=true;$('hud').hidden=false;last=performance.now();acc=0;}
function pause(){if(!started)return;paused=true;cancelInput();persist();$('modal').hidden=false;$('start').textContent='Voltar aos campos';$('menuText').textContent='Sua aventura está esperando por você.';$('save').hidden=false;$('new').hidden=false;}
$('start').onclick=play;$('new').onclick=()=>{if(confirm('Começar outra aventura? Seu progresso salvo será substituído.')){Module._game_new();won=false;persist();play();}};
$('pause').onclick=pause;$('save').onclick=persist;
$('quest').onclick=()=>{showQuest=!showQuest;$('objectives').hidden=!showQuest;};
$('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else if(document.documentElement.requestFullscreen)await document.documentElement.requestFullscreen();}catch{}resize();};
$('help').onclick=()=>{$('guide').hidden=false;};$('closeGuide').onclick=()=>{$('guide').hidden=true;};
$('leaveWorkshop').onclick=()=>{$('workshop').hidden=true;play();};
function updateWorkshop(){const p=state.player;$('wallet').textContent=`${p.coins} moedas · vida restaurada`;const names=['Vida +25','Ataque +8','Velocidade +15'],levels=[p.healthUp,p.attackUp,p.speedUp];document.querySelectorAll('[data-upgrade]').forEach((b,i)=>{b.innerHTML=`${names[i]} <small>Nível ${levels[i]}/5 · ${levels[i]>=5?'Máximo':`${30+levels[i]*25} moedas`}</small>`;b.disabled=levels[i]>=5||p.coins<30+levels[i]*25;});}
for(const button of document.querySelectorAll('[data-upgrade]'))button.onclick=()=>{Module._game_upgrade(+button.dataset.upgrade);state=api.snapshot(w/scale,h/scale);persist();updateWorkshop();};
function workshop(){paused=true;cancelInput();$('workshop').hidden=false;updateWorkshop();}
canvas.addEventListener('pointerdown',e=>{if(paused)return;e.preventDefault();canvas.setPointerCapture(e.pointerId);const action=Module._game_pointer_down(e.pointerId,e.clientX,e.clientY);pointers.set(e.pointerId,action);if(action===5)workshopRequested=true;if(!action&&e.pointerType==='mouse'){mouseAttack=true;mouseWorld={x:e.clientX,y:e.clientY};}});
canvas.addEventListener('pointermove',e=>{if(paused)return;Module._game_pointer_move(e.pointerId,e.clientX,e.clientY);if(mouseAttack&&!pointers.get(e.pointerId))mouseWorld={x:e.clientX,y:e.clientY};});
function release(e){Module._game_pointer_up(e.pointerId);if(!pointers.get(e.pointerId))mouseAttack=false;pointers.delete(e.pointerId);}
canvas.addEventListener('pointerup',release);canvas.addEventListener('pointercancel',release);canvas.addEventListener('lostpointercapture',release);canvas.addEventListener('contextmenu',e=>e.preventDefault());
addEventListener('blur',()=>{if(started&&!paused)pause();else cancelInput();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&started)pause();});addEventListener('pagehide',()=>{if(started)persist();});
addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' ','Shift'].includes(e.key))e.preventDefault();if(e.key==='Escape'){if(paused)play();else pause();return;}if(paused)return;keys.add(e.key.toLowerCase());if(!e.repeat){if(e.key==='Shift')pulses|=2;if(e.key.toLowerCase()==='q')pulses|=4;if(e.key.toLowerCase()==='e'){pulses|=8;workshopRequested=true;}}});addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));
const oval=(x,y,rx,ry,color)=>{ctx.fillStyle=color;ctx.beginPath();ctx.ellipse(x,y,rx,ry,0,0,Math.PI*2);ctx.fill();};
const rect=(x,y,ww,hh,c)=>{ctx.fillStyle=c;ctx.fillRect(x,y,ww,hh);};
const line=(x,y,x2,y2,width,c)=>{ctx.strokeStyle=c;ctx.lineWidth=width;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x2,y2);ctx.stroke();};
function label(text,x,y,size,color='#faf3d7'){ctx.fillStyle=color;ctx.font=`600 ${size}px system-ui`;ctx.textAlign='center';ctx.fillText(text,x,y);}
function chicken(x,y,fx,fy,moving,time,size=80,tint=false,action=-1,progress=0){let img=walk,row=Math.abs(fx)>Math.abs(fy)?(fx<0?1:3):(fy<0?2:0),frame=moving?Math.floor(time*9)%4:0,flip=false;if(action>=0){img=actions;row=action;frame=Math.min(3,Math.max(0,Math.floor(progress*4)));flip=fx<0;}
 const cw=img.width/4,ch=img.height/4;oval(x+3,y+8,size*.28,size*.1,'#15391f55');ctx.save();ctx.translate(x,y+12);if(flip)ctx.scale(-1,1);if(tint)ctx.globalAlpha=.6;ctx.drawImage(img,frame*cw,row*ch,cw,ch,-size/2,-size*.94,size,size);ctx.restore();}
function tree(x,y,hash,time){const sway=Math.sin(time*.7+hash%100)*.7;oval(x+14,y+12,42,20,'#1b3d1f50');rect(x-8,y-35,17,42,'#684428');rect(x-5,y-35,5,41,'#a36730');oval(x+sway,y-46,45,33,'#1c5133');oval(x-15+sway,y-55,29,30,'#2a733a');oval(x+19+sway,y-53,27,29,'#2d7c40');oval(x+sway,y-73,31,29,'#409342');oval(x-9+sway,y-82,19,17,'#58aa4c');oval(x-14+sway,y-87,10,8,'#6fbe56');if(hash%3===0){oval(x-20,y-63,4,4,'#ec5e43');oval(x+16,y-74,4,4,'#f26c48');}}
function loot(x,y,kind,time){const bob=Math.sin(time*3+x)*2;oval(x+1,y+8,13,5,'#13362140');y+=bob;if(kind<2){oval(x,y,9,13,kind===1?'#ab6f1f':'#b6a27a');oval(x,y-2,8,12,kind===1?'#ffcf59':'#faf3d7');oval(x-3,y-5,2,4,'#fffde7');if(kind===1){line(x+15,y-15,x+15,y-7,2,'#ffcf59');line(x+11,y-11,x+19,y-11,2,'#ffcf59');}}else if(kind===2){ctx.fillStyle='#ee7e2c';ctx.beginPath();ctx.moveTo(x-8,y-8);ctx.lineTo(x+9,y-5);ctx.lineTo(x+1,y+14);ctx.fill();line(x,y-6,x-7,y-17,4,'#368342');line(x+1,y-6,x+7,y-18,4,'#59ab49');}else{rect(x-16,y-11,32,23,'#5e3620');rect(x-16,y-15,32,14,'#9c5926');rect(x-13,y-14,3,25,'#ffcf59');rect(x+10,y-14,3,25,'#ffcf59');rect(x-4,y-5,8,9,'#ffcf59');}}
function house(){const x=160,y=30;oval(x+12,y+20,77,32,'#14331f50');rect(x-61,y-64,122,84,'#8e5a30');rect(x-56,y-61,111,73,'#d2a355');for(let i=0;i<5;i++)line(x-53,y-48+i*14,x+53,y-48+i*14,2,'#ae7c3f');rect(x-16,y-27,33,48,'#453125');rect(x-19,y+17,39,8,'#ab9162');rect(x+29,y-42,20,23,'#47717b');ctx.fillStyle='#d36d41';ctx.beginPath();ctx.moveTo(x-76,y-60);ctx.lineTo(x,y-119);ctx.lineTo(x+76,y-60);ctx.fill();for(let i=0;i<4;i++)line(x-58+i*11,y-73-i*9,x+58-i*11,y-73-i*9,3,'#e88b4f');label('LAR, DOCE NINHO',x,y-7,8);}
function drawWorld(s){const p=s.player,cx=s.camera[0],cy=s.camera[1],time=s.time;ctx.save();ctx.translate(w/2,h/2);ctx.scale(scale,scale);ctx.translate(-cx,-cy);
 const objects=[];for(const [tx,ty,type,hash]of s.tiles){const x=tx*64,y=ty*64,shade=hash%7;let color=type===3?'#3189a0':type===2?`rgb(${203+shade},${174+shade},${100+shade})`:type===1?`rgb(${137+shade},${177+shade},${78+shade})`:`rgb(${101+shade},${159+shade},${71+shade})`;rect(x,y,64.5,64.5,color);if(type===3){let phase=Math.sin(time*1.5+tx+ty)*4;line(x+9+phase,y+20,x+27+phase,y+20,2,'#6cbab691');line(x+34-phase,y+45,x+49-phase,y+45,2,'#63b8bc99');}else if(type!==2){for(let i=0;i<3;i++){const gx=(hash>>>(i*4))%52+6,gy=(hash>>>(i*5+2))%52+6;line(x+gx,y+gy,x+gx-2,y+gy-5,1.5,'#48853c88');}if(hash%9===0){oval(x+22,y+35,3,3,'#f6dca4');oval(x+27,y+38,3,3,'#f1c498');}}
 if(type===4)objects.push({y:y+32,draw:()=>tree(x+32,y+32,hash,time)});if(type===5)objects.push({y:y+32,draw:()=>{oval(x+37,y+40,26,13,'#213a2050');oval(x+32,y+32,25,20,'#65736b');oval(x+29,y+26,23,15,'#a0a78a');oval(x+25,y+22,13,8,'#babb9c');}});}
 oval(160,164,110,64,'#cbad626e');for(let i=0;i<10;i++){const a=i*Math.PI*2/10;oval(1250+Math.cos(a)*167,-550+Math.sin(a)*150,20,13,'#7d8c73');oval(1250+Math.cos(a)*167,-553+Math.sin(a)*150,19,12,'#b9ba92');}
 objects.push({y:65,draw:house},{y:215,draw:()=>{chicken(86,215,.7,-.2,false,time,80);label('Dona Cocó',86,155,13);}});
 objects.push({y:1145,draw:()=>{for(const side of[-85,85]){rect(-1050+side-19,1075,38,73,'#788573');rect(-1050+side-16,1077,13,70,'#b9bc9d');rect(-1050+side-25,1069,50,12,'#a1ab8b');}label('POMAR ESQUECIDO',-1050,1083,14,'#ffcf59');}});
 for(const [x,y,kind]of s.loot)if(Math.abs(x-cx)<w/scale/2+90&&Math.abs(y-cy)<h/scale/2+90)objects.push({y,draw:()=>loot(x,y,kind,time)});
 for(const [x,y,fx,fy,hp,maxHp,boss,brain,tier]of s.enemies)if(Math.abs(x-cx)<w/scale/2+120&&Math.abs(y-cy)<h/scale/2+120)objects.push({y,draw:()=>{if(brain===2){oval(x,y,boss?104:74,boss?74:48,'#e0412d55');line(x,y,x+fx*(boss?105:76),y+fy*(boss?105:76),8,'#ff7c4baa');}ctx.save();ctx.filter=boss?'hue-rotate(240deg)':'sepia(.5)';chicken(x,y,fx,fy,brain===1,time, boss?110:75);ctx.restore();if(boss){label('♛',x,y-102,26,'#ffcf59');label(p.ready?'GUARDIÃO':'GUARDIÃO · SELADO',x,y-116,11,'#ffcf59');}if(hp<maxHp||boss){rect(x-28,y-(boss?94:68),56,5,'#162723');rect(x-28,y-(boss?94:68),56*hp/maxHp,5,'#e7674b');}}});
 let action=p.attack>0?0:p.dodge>0?1:p.invulnerable>.3?2:p.bossDefeated&&!p.moving?3:-1,progress=p.attack>0?( .18-p.attack)/.18:p.dodge>0?(.2-p.dodge)/.2:(time*4)%1;
 objects.push({y:p.y,draw:()=>{chicken(p.x,p.y,p.fx,p.fy,p.moving,p.walkTime,80,p.invulnerable>0&&Math.floor(time*16)%2===0,action,progress);if(p.attack>0){const a=Math.atan2(p.fy,p.fx),r=56+(1-p.attack/.18)*26;ctx.strokeStyle='#fff8d2';ctx.lineWidth=5;ctx.beginPath();ctx.arc(p.x,p.y,r,a-1,a+1);ctx.stroke();}}});
 objects.sort((a,b)=>a.y-b.y);for(const o of objects)o.draw();for(const[x,y,life,kind,text]of s.effects){ctx.globalAlpha=life;if(text)label(text,x,y-48,16,kind===1?'#ff8065':kind===3?'#88de9d':'#ffcf59');else oval(x,y,18,9,'#ffcf59');}ctx.globalAlpha=1;
 // Offscreen direction markers make the home and arena discoverable on small screens.
 for(const [x,y,color,name]of[[160,160,'#7bd0ff','NINHO'],[1250,-550,'#ffcf59','GUARDIÃO']]){const dx=x-cx,dy=y-cy,dist=Math.hypot(dx,dy);if(dist<130)continue;const maxX=w/scale/2-35,maxY=h/scale/2-145;const factor=Math.min(1,maxX/Math.max(1,Math.abs(dx)),maxY/Math.max(1,Math.abs(dy)));const px=cx+dx*factor,py=cy+dy*factor;oval(px,py,7,7,color);label(name,px,py-12,10,color);}
 ctx.restore();}
function controls(s){const c=s.controls,r=c.radius;oval(...c.stick,r,r,'#11222890');oval(...c.stick,r*.76,r*.76,'#699d8540');oval(...c.knob,r*.44,r*.44,'#d6ead0cf');const button=(pos,size,labelText,active)=>{oval(...pos,size,size,active?'#e2a13aee':'#18312dda');oval(...pos,size-3,size-3,active?'#eeb34dee':'#466a59ba');label(labelText,pos[0],pos[1]+4,size>45?14:10);};button(c.attack,r*.85,'BICAR',c.attacking);button(c.dodge,r*.56,'ESQUIVA',false);button(c.eat,r*.56,'COMER',false);button(c.interact,r*.56,'USAR',false);}
function updateHud(s){const p=s.player;$('level').textContent=`NV. ${p.level}`;$('health').style.width=`${p.hp/p.maxHp*100}%`;$('energy').style.width=`${p.stamina}%`;$('stats').textContent=`${Math.ceil(p.hp)}/${p.maxHp} vida · ${p.coins} moedas · ${p.food} alimentos`;$('questText').innerHTML=`${Math.min(p.eggs,6)}/6 ovos<br>${Math.min(p.gold,2)}/2 ovos de ouro<br>${Math.min(p.kills,5)}/5 rivais vencidos${p.bossDefeated?'<br>✓ Guardião vencido!':''}`;$('message').textContent=s.message;$('message').style.opacity=s.message&&!showQuest?1:0;}
function frame(now){let dt=Math.min(.1,Math.max(0,(now-last)/1000));last=now;
 if(!paused){acc+=dt;let first=true;while(acc>=1/60){let flags=(keys.has(' ')?1:0)|(mouseAttack?1:0)|(first?pulses:0);let ax=0,ay=0;if(mouseAttack&&state&&mouseWorld){ax=(mouseWorld.x-w/2)/scale+state.camera[0]-state.player.x;ay=(mouseWorld.y-h/2)/scale+state.camera[1]-state.player.y;}Module._game_tick(1/60,Number(keys.has('d')||keys.has('arrowright'))-Number(keys.has('a')||keys.has('arrowleft')),Number(keys.has('s')||keys.has('arrowdown'))-Number(keys.has('w')||keys.has('arrowup')),flags,ax,ay);acc-=1/60;first=false;}if(!first)pulses=0;autosave+=dt;}
 state=api.snapshot(w/scale,h/scale);rect(0,0,w,h,'#203e32');drawWorld(state);if(started){controls(state);updateHud(state);}
 if(!paused){if(autosave>=45||Module._game_needs_save()){persist();autosave=0;}if(workshopRequested){workshopRequested=false;if(state.player.atNest)workshop();}if(state.player.bossDefeated&&!won){won=true;pause();$('menuText').textContent='Você venceu o Guardião! Continue explorando seu galinheiro lendário.';}}
 requestAnimationFrame(frame);}
requestAnimationFrame(frame);
// Integration hooks for browser tests; gameplay runs in C++.
window.granjaDebug={get state(){return state;},get paused(){return paused;},module:Module};
