export class OnlineGame {
 constructor(url,onStatus){this.url=url;this.onStatus=onStatus;this.key=`granja-session:${url.origin}`;this.state=null;this.ready=false;this.input={mx:0,my:0,ax:0,ay:0,flags:0};this.lastSend=0;this.attempt=0;this.onState=()=>{};}
 async connect(){return new Promise((resolve,reject)=>{this.resolve=resolve;this.reject=reject;this.open();});}
 open(){const ws=this.ws=new WebSocket(this.url);const timeout=setTimeout(()=>ws.close(),15000);ws.onopen=()=>{let token;try{token=localStorage.getItem(this.key);}catch{}ws.send(JSON.stringify({type:'hello',token,name:'Galinha'}));};
 ws.onmessage=e=>{const packet=JSON.parse(e.data);if(packet.type==='welcome'){this.id=packet.id;try{localStorage.setItem(this.key,packet.token);}catch{}return;}if(packet.type==='error'){this.onStatus(packet.message);return;}if(packet.type==='state'){packet.state.tiles??=this.state?.tiles||[];this.state=packet.state;if(!this.ready){clearTimeout(timeout);this.ready=true;this.attempt=0;this.resolve?.();this.resolve=null;this.onStatus('Conectado ao mundo.');}this.onState();}};
 ws.onclose=()=>{clearTimeout(timeout);this.ready=false;this.input={mx:0,my:0,ax:0,ay:0,flags:0};this.onStatus('Conexão interrompida. Retomando seu progresso…');if(this.resolve){this.reject(new Error('Servidor indisponível. Verifique o endereço e tente novamente.'));this.resolve=null;return;}if(!this.stopped)setTimeout(()=>this.open(),Math.min(10000,500*2**this.attempt++));};}
 send(type,fields={}){if(this.ready&&this.ws.readyState===WebSocket.OPEN)this.ws.send(JSON.stringify({type,...fields}));}
 submit(input){this.input={...input,flags:(this.input.flags&14)|input.flags};if(performance.now()-this.lastSend>=50){this.send('input',{input:this.input});this.input.flags&=1;this.lastSend=performance.now();}}
 snapshot(controls){if(!this.state)return null;return{...this.state,controls};}
}
export function onlineEndpoint(){const explicit=new URLSearchParams(location.search).get('server'),local=document.querySelector('meta[name="granja-server"]')?.content;if(!explicit&&!local)return null;const url=new URL(explicit||local,location.href);if(url.protocol==='http:')url.protocol='ws:';if(url.protocol==='https:')url.protocol='wss:';if(!['ws:','wss:'].includes(url.protocol)||location.protocol==='https:'&&url.protocol!=='wss:')throw new Error('Use um servidor WebSocket seguro (wss).');return url;}
